# Generated by Django 5.2.16 on 2026-07-18 15:50

import Plateform_medicale.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanCouverture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('taux_couverture', models.DecimalField(decimal_places=2, help_text="Pourcentage des frais pris en charge par l'assurance (ex: 90.00 pour 90%).", max_digits=5, verbose_name='taux de couverture (%)')),
                ('plafond_annuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='plafond annuel')),
            ],
            options={
                'verbose_name': 'plan de couverture',
                'verbose_name_plural': 'plans de couverture',
            },
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_prestataire', models.CharField(choices=[('HOPITAL', 'Hopital'), ('CLINIQUE', 'Clinique'), ('PHARMACIE', 'Pharmacie'), ('CABINET', 'Cabinet medical')], max_length=20, verbose_name="type d'etablissement")),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('partenaire', models.BooleanField(default=True, help_text='Fait partie du reseau conventionne.', verbose_name='partenaire actif')),
                ('date_conventionnement', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'prestataire',
                'verbose_name_plural': 'prestataires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField()),
                ('diagnostic', models.TextField()),
                ('traitement', models.TextField(blank=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plateform_medicale.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicaments', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plateform_medicale.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('type_beneficiaire', models.CharField(choices=[('PRINCIPAL', 'Assure principal'), ('AYANT_DROIT', 'Ayant droit')], default='PRINCIPAL', max_length=20)),
                ('lien_parente', models.CharField(blank=True, choices=[('CONJOINT', 'Conjoint(e)'), ('ENFANT', 'Enfant'), ('AUTRE', 'Autre')], default='', max_length=20)),
                ('numero_carte', models.CharField(editable=False, max_length=30, unique=True, verbose_name='numero de carte de prise en charge')),
                ('assure_principal', models.ForeignKey(blank=True, help_text="Renseigne uniquement pour un ayant droit : l'assure principal rattache.", limit_choices_to={'type_beneficiaire': 'PRINCIPAL'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ayants_droit', to='Plateform_medicale.patient')),
                ('plan_couverture', models.ForeignKey(blank=True, help_text="Renseigne pour l'assure principal ; les ayants droit heritent de ce plan.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaires', to='Plateform_medicale.plancouverture')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plateform_medicale.patient'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins', to='Plateform_medicale.prestataire'),
        ),
        migrations.CreateModel(
            name='PriseEnCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validee'), ('refusee', 'Refusee'), ('terminee', 'Terminee')], default='en_attente', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plateform_medicale.patient')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='prise_en_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plateform_medicale.priseencharge'),
        ),
        migrations.CreateModel(
            name='ServiceMedical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prestataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='Plateform_medicale.prestataire')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plateform_medicale.servicemedical'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='nom')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('ASSURE', 'Assuré'), ('MEDECIN', 'Médecin'), ('PHARMACIEN', 'Pharmacien')], db_index=True, max_length=20, verbose_name='rôle')),
                ('is_staff', models.BooleanField(default=False, verbose_name='accès au back-office')),
                ('is_active', models.BooleanField(default=True, verbose_name='compte actif')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', Plateform_medicale.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmaciens', to='Plateform_medicale.prestataire')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pharmacien',
                'verbose_name_plural': 'pharmaciens',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Compte de connexion associe (assure principal uniquement).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medecin',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecin', to=settings.AUTH_USER_MODEL),
        ),
    ]
