# Generated by Django 5.2.16 on 2026-07-18 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='code_qr',
            field=models.CharField(default='', editable=False, help_text="Encode dans le QR scanne par la pharmacie pour valider l'ordonnance.", max_length=20, unique=True, verbose_name='code de verification'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(verbose_name='date et heure')),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demande'), ('CONFIRME', 'Confirme'), ('ANNULE', 'Annule'), ('TERMINE', 'Termine')], default='DEMANDE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='Plateform_medicale.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='Plateform_medicale.patient')),
                ('prestataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='Plateform_medicale.prestataire')),
            ],
            options={
                'verbose_name': 'rendez-vous',
                'verbose_name_plural': 'rendez-vous',
                'ordering': ['date_heure'],
            },
        ),
    ]
