# Generated by Django 5.2.16 on 2026-07-18 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0002_ordonnance_code_qr_rendezvous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plateform_medicale.servicemedical'),
        ),
    ]
