# Generated by Django 5.2.16 on 2026-07-18 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0003_alter_consultation_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_delivrance', models.DateTimeField(auto_now_add=True)),
                ('ordonnance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivrance', to='Plateform_medicale.ordonnance')),
                ('pharmacien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivrances', to='Plateform_medicale.pharmacien')),
            ],
            options={
                'verbose_name': 'delivrance',
                'verbose_name_plural': 'delivrances',
                'ordering': ['-date_delivrance'],
            },
        ),
    ]
