# Generated by Django 5.2.16 on 2026-07-18 21:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='telephone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numero de telephone invalide (chiffres, espaces, tirets et + uniquement).', regex='^\\+?[0-9 \\-]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Numero de telephone invalide (chiffres, espaces, tirets et + uniquement).', regex='^\\+?[0-9 \\-]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_beneficiaire',
            field=models.CharField(choices=[('PRINCIPAL', 'Assure principal'), ('AYANT_DROIT', 'Ayant droit')], db_index=True, default='PRINCIPAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacien',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacien', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Numero de telephone invalide (chiffres, espaces, tirets et + uniquement).', regex='^\\+?[0-9 \\-]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='priseencharge',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validee'), ('refusee', 'Refusee'), ('terminee', 'Terminee')], db_index=True, default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('DEMANDE', 'Demande'), ('CONFIRME', 'Confirme'), ('ANNULE', 'Annule'), ('TERMINE', 'Termine')], db_index=True, default='DEMANDE', max_length=20),
        ),
    ]
