# Generated by Django 5.2.16 on 2026-07-19 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0007_alter_medecin_telephone_alter_patient_telephone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taux_applique', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='taux de couverture applique (%)')),
                ('montant_part_assurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_part_patient', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('non_regle', 'Non regle'), ('regle', 'Regle')], db_index=True, default='non_regle', max_length=20)),
                ('mode_reglement', models.CharField(blank=True, choices=[('ESPECES', 'Especes'), ('MOBILE_MONEY', 'Mobile money'), ('CARTE', 'Carte bancaire'), ('VIREMENT', 'Virement')], max_length=20)),
                ('date_reglement', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='Plateform_medicale.consultation')),
            ],
        ),
    ]
