# Generated by Django 5.2.16 on 2026-07-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0008_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Renseignee en placant un point sur la carte (formulaire prestataire).', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
