# Generated by Django 5.2.16 on 2026-08-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0009_prestataire_latitude_prestataire_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode_reglement',
            field=models.CharField(blank=True, choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile money'), ('CARTE', 'Carte bancaire'), ('VIREMENT', 'Virement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('non_regle', 'Non réglé'), ('regle', 'Réglé')], db_index=True, default='non_regle', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_beneficiaire',
            field=models.CharField(choices=[('PRINCIPAL', 'Assuré principal'), ('AYANT_DROIT', 'Ayant droit')], db_index=True, default='PRINCIPAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='type_prestataire',
            field=models.CharField(choices=[('HOPITAL', 'Hôpital'), ('CLINIQUE', 'Clinique'), ('PHARMACIE', 'Pharmacie'), ('CABINET', 'Cabinet médical')], max_length=20, verbose_name="type d'etablissement"),
        ),
        migrations.AlterField(
            model_name='priseencharge',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('terminee', 'Terminée')], db_index=True, default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('DEMANDE', 'Demande'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], db_index=True, default='DEMANDE', max_length=20),
        ),
    ]
