# Generated by Django 5.2.16 on 2026-08-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0010_alter_paiement_mode_reglement_alter_paiement_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativeConnexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='adresse saisie')),
                ('tentatives', models.PositiveSmallIntegerField(default=0, verbose_name='échecs consécutifs')),
                ('dernier_echec', models.DateTimeField(auto_now=True, verbose_name='dernier échec')),
            ],
            options={
                'verbose_name': 'tentative de connexion',
                'verbose_name_plural': 'tentatives de connexion',
                'ordering': ['-dernier_echec'],
            },
        ),
    ]
