# Generated by Django 5.2.16 on 2026-08-16 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0011_tentativeconnexion'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur_libelle', models.CharField(max_length=254, verbose_name='auteur (figé)')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('ACTIVATION', 'Activation'), ('DESACTIVATION', 'Désactivation'), ('DEBLOCAGE', 'Déblocage'), ('MOT_DE_PASSE', 'Mot de passe réinitialisé'), ('DECISION', 'Décision'), ('REGLEMENT', 'Règlement'), ('IMPORT', 'Import en masse')], db_index=True, max_length=20)),
                ('objet', models.CharField(max_length=200, verbose_name='objet concerné')),
                ('details', models.CharField(blank=True, max_length=300, verbose_name='détail')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_journalisees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrée du journal',
                'verbose_name_plural': "journal d'activité",
                'ordering': ['-date'],
            },
        ),
    ]
