# Generated by Django 5.2.16 on 2026-08-17 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0013_alter_journalactivite_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='medicaments',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=200, verbose_name='médicament')),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('posologie', models.CharField(blank=True, max_length=200)),
                ('duree', models.CharField(blank=True, max_length=100, verbose_name='durée')),
                ('quantite', models.CharField(blank=True, max_length=50, verbose_name='quantité')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='Plateform_medicale.ordonnance')),
            ],
            options={
                'verbose_name': "ligne d'ordonnance",
                'verbose_name_plural': "lignes d'ordonnance",
                'ordering': ['ordre', 'pk'],
            },
        ),
    ]
