# Generated by Django 5.2.16 on 2026-08-17 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0014_alter_ordonnance_medicaments_ligneordonnance'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='annees_experience',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Laisser vide si l'information n'est pas connue.", null=True, verbose_name="années d'expérience"),
        ),
        migrations.AddField(
            model_name='medecin',
            name='presentation',
            field=models.TextField(blank=True, help_text="Texte libre affiche a l'assure qui choisit son medecin.", verbose_name='présentation'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, help_text="Qui a constate le reglement. Renseigne automatiquement, jamais saisi. SET_NULL : supprimer un compte n'efface pas l'ecriture.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='motif',
            field=models.TextField(blank=True, help_text="Decrit par le PATIENT lors de sa demande. Ce n'est pas un diagnostic : le diagnostic appartient au medecin et vit dans Consultation.diagnostic.", verbose_name='motif / symptômes'),
        ),
    ]
