# Generated by Django 5.2.16 on 2026-08-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0015_medecin_annees_experience_medecin_presentation_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rendezvous',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'ANNULE'), _negated=True), fields=('medecin', 'date_heure'), name='rdv_creneau_unique_par_medecin', violation_error_message='Ce créneau est déjà réservé pour ce médecin. Choisissez une autre date ou une autre heure.'),
        ),
    ]
