# Generated by Django 5.2.16 on 2026-08-24 17:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0016_rendezvous_rdv_creneau_unique_par_medecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_envoye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_erreur',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre',
            field=models.CharField(default='Notification', max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='type_evenement',
            field=models.CharField(choices=[('RDV_DEMANDE', 'Demande de rendez-vous'), ('RDV_CONFIRME', 'Rendez-vous confirmé'), ('RDV_REFUSE', 'Rendez-vous refusé'), ('RDV_ANNULE', 'Rendez-vous annulé'), ('PEC_DEMANDE', 'Demande de prise en charge'), ('PEC_VALIDEE', 'Prise en charge validée'), ('PEC_REFUSEE', 'Prise en charge refusée'), ('ORDONNANCE_CREEE', 'Nouvelle ordonnance'), ('DELIVRANCE_EFFECTUEE', 'Délivrance effectuée'), ('SYSTEME', 'Notification système')], default='SYSTEME', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='url_action',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='servicemedical',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Le prix ne peut pas être négatif.')]),
        ),
        migrations.CreateModel(
            name='PreferenceNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_rdv', models.BooleanField(default=True)),
                ('email_prise_en_charge', models.BooleanField(default=True)),
                ('email_ordonnance', models.BooleanField(default=True)),
                ('email_delivrance', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
