# Generated by Django 5.2.16 on 2026-08-25 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0017_notification_email_envoye_notification_email_erreur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date d'annulation"),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='motif_annulation',
            field=models.CharField(blank=True, max_length=255, verbose_name="motif d'annulation"),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='statut',
            field=models.CharField(choices=[('actif', 'En attente de délivrance'), ('delivre', 'Délivrée en pharmacie'), ('annule', 'Annulée par le médecin')], db_index=True, default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='Plateform_medicale.consultation'),
        ),
    ]
