# Generated by Django 5.2.16 on 2026-09-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0018_ordonnance_date_annulation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rendezvous',
            name='rdv_creneau_unique_par_medecin',
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('DEMANDE', 'Demande'), ('CONFIRME', 'Confirmé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], db_index=True, default='DEMANDE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='rendezvous',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['ANNULE', 'REFUSE']), _negated=True), fields=('medecin', 'date_heure'), name='rdv_creneau_unique_par_medecin', violation_error_message='Ce créneau est déjà réservé pour ce médecin. Choisissez une autre date ou une autre heure.'),
        ),
    ]
