# Generated by Django 5.2.16 on 2026-09-13 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0019_remove_rendezvous_rdv_creneau_unique_par_medecin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_evenement',
            field=models.CharField(choices=[('RDV_DEMANDE', 'Demande de rendez-vous'), ('RDV_CONFIRME', 'Rendez-vous confirmé'), ('RDV_REFUSE', 'Rendez-vous refusé'), ('RDV_ANNULE', 'Rendez-vous annulé'), ('PEC_DEMANDE', 'Demande de prise en charge'), ('PEC_VALIDEE', 'Prise en charge validée'), ('PEC_REFUSEE', 'Prise en charge refusée'), ('ORDONNANCE_CREEE', 'Nouvelle ordonnance'), ('DELIVRANCE_EFFECTUEE', 'Délivrance effectuée'), ('SUPPORT_DEMANDE', "Nouvelle demande d'assistance"), ('SUPPORT_REPONSE', "Réponse de l'administration"), ('SYSTEME', 'Notification système')], default='SYSTEME', max_length=30),
        ),
        migrations.CreateModel(
            name='DemandeSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(editable=False, max_length=20, unique=True)),
                ('objet', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('RDV', 'Rendez-vous'), ('PEC', 'Prise en charge & Remboursement'), ('ORDONNANCE', 'Ordonnance & Pharmacie'), ('COMPTE', "Carte d'assuré & Données du compte"), ('AYANT_DROIT', 'Ayants droit & Famille'), ('TECHNIQUE', 'Problème technique'), ('AUTRE', 'Autre demande')], db_index=True, default='AUTRE', max_length=20)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('URGENTE', 'Urgente')], db_index=True, default='NORMALE', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('REPONDU', 'Réponse envoyée'), ('FERME', 'Clôturée')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('cloture_le', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_support', to=settings.AUTH_USER_MODEL)),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_support', to='Plateform_medicale.patient')),
            ],
            options={
                'verbose_name': 'demande de support',
                'verbose_name_plural': 'demandes de support',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MessageSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_support', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Plateform_medicale.demandesupport')),
            ],
            options={
                'verbose_name': 'message de support',
                'verbose_name_plural': 'messages de support',
                'ordering': ['date_envoi'],
            },
        ),
    ]
