# Generated by Django 5.2.16 on 2026-09-16 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0020_alter_notification_type_evenement_demandesupport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priseencharge',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priseencharge',
            name='motif_refus',
            field=models.CharField(blank=True, max_length=255, verbose_name='motif de refus'),
        ),
        migrations.AddField(
            model_name='priseencharge',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prises_en_charge_validees', to=settings.AUTH_USER_MODEL),
        ),
    ]
