# Generated by Django 5.2.16 on 2026-09-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0021_priseencharge_date_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='type_admission',
            field=models.CharField(choices=[('RDV', 'Sur rendez-vous'), ('SPONTANE', 'Passage spontané'), ('URGENCE', 'Urgence médicale')], db_index=True, default='RDV', max_length=20, verbose_name="type d'admission"),
        ),
    ]
