# Generated by Django 5.2.16 on 2026-09-25 18:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0023_remove_rendezvous_rdv_creneau_unique_par_medecin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivrance',
            name='montant_part_assurance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Part prise en charge / IPM (FCFA)'),
        ),
        migrations.AddField(
            model_name='delivrance',
            name='montant_part_patient',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Part payée par le patient / Ticket modérateur (FCFA)'),
        ),
        migrations.AddField(
            model_name='delivrance',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant total des médicaments (FCFA)'),
        ),
        migrations.AddField(
            model_name='delivrance',
            name='taux_couverture',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Taux de prise en charge appliqué (%)'),
        ),
        migrations.AlterField(
            model_name='delivrance',
            name='pharmacien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivrances', to='Plateform_medicale.pharmacien'),
        ),
    ]
