# Generated by Django 5.2.16 on 2026-09-26 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0024_delivrance_montant_part_assurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_decision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de décision'),
        ),
        migrations.AddField(
            model_name='patient',
            name='document_justificatif',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs_ayants_droit/', verbose_name='pièce justificative (état civil / scolarité)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='motif_refus',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='motif de refus'),
        ),
        migrations.AddField(
            model_name='patient',
            name='statut_validation',
            field=models.CharField(choices=[('VALIDE', 'Validé'), ('EN_ATTENTE', 'En attente de validation'), ('REFUSE', 'Refusé')], db_index=True, default='VALIDE', max_length=20, verbose_name='statut de validation IPM'),
        ),
        migrations.AddField(
            model_name='patient',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ayants_droit_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_evenement',
            field=models.CharField(choices=[('RDV_DEMANDE', 'Demande de rendez-vous'), ('RDV_CONFIRME', 'Rendez-vous confirmé'), ('RDV_REFUSE', 'Rendez-vous refusé'), ('RDV_ANNULE', 'Rendez-vous annulé'), ('PEC_DEMANDE', 'Demande de prise en charge'), ('PEC_VALIDEE', 'Prise en charge validée'), ('PEC_REFUSEE', 'Prise en charge refusée'), ('ORDONNANCE_CREEE', 'Nouvelle ordonnance'), ('DELIVRANCE_EFFECTUEE', 'Délivrance effectuée'), ('SUPPORT_DEMANDE', "Nouvelle demande d'assistance"), ('SUPPORT_REPONSE', "Réponse de l'administration"), ('AYANT_DROIT_SOUMIS', "Demande d'ayant droit soumise"), ('AYANT_DROIT_VALIDE', "Ayant droit validé par l'IPM"), ('AYANT_DROIT_REFUSE', "Ayant droit refusé par l'IPM"), ('SYSTEME', 'Notification système')], default='SYSTEME', max_length=30),
        ),
    ]
