# Generated by Django 5.2.16 on 2026-09-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0025_patient_date_decision_patient_document_justificatif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin', models.CharField(db_index=True, max_length=255, unique=True)),
                ('contenu', models.BinaryField()),
                ('type_mime', models.CharField(default='application/octet-stream', max_length=120)),
                ('taille', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'fichier média persistant',
                'verbose_name_plural': 'fichiers médias persistants',
                'ordering': ['-date_creation'],
            },
        ),
    ]
