# Generated by Django 5.2.16 on 2026-10-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0026_fichiermedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='priseencharge',
            name='devis_fichier',
            field=models.FileField(blank=True, help_text="Fichier du devis fourni par l'établissement (PDF, JPG, PNG - max 10 Mo).", null=True, upload_to='devis_prises_en_charge/', verbose_name='devis médical (PDF ou scan)'),
        ),
        migrations.AddField(
            model_name='priseencharge',
            name='montant_estime',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant estimatif figurant sur le devis remis par la structure de soins.', max_digits=12, null=True, verbose_name='montant estimé du devis'),
        ),
        migrations.AddField(
            model_name='priseencharge',
            name='numero_pec',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='numéro de prise en charge'),
        ),
    ]
