# Generated by Django 5.2.16 on 2026-10-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0027_priseencharge_devis_fichier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priseencharge',
            name='motif',
            field=models.TextField(blank=True, default='', verbose_name='détails ou notes'),
        ),
    ]
