# Generated by Django 5.2.16 on 2026-10-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0028_alter_priseencharge_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='sceau',
            field=models.CharField(blank=True, editable=False, help_text="HMAC-SHA256 du contenu de l'ordonnance au moment de la prescription.", max_length=64, verbose_name="sceau d'intégrité"),
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='action',
            field=models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('ACTIVATION', 'Activation'), ('DESACTIVATION', 'Désactivation'), ('DEBLOCAGE', 'Déblocage'), ('MOT_DE_PASSE', 'Mot de passe réinitialisé'), ('DECISION', 'Décision'), ('REGLEMENT', 'Règlement'), ('IMPORT', 'Import en masse'), ('CARTE', 'Carte éditée'), ('INTEGRITE', "Alerte d'intégrité")], db_index=True, max_length=20),
        ),
    ]
