# Generated by Django 5.2.16 on 2026-10-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plateform_medicale', '0029_ordonnance_sceau_integrite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalactivite',
            name='action',
            field=models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('ACTIVATION', 'Activation'), ('DESACTIVATION', 'Désactivation'), ('DEBLOCAGE', 'Déblocage'), ('MOT_DE_PASSE', 'Mot de passe réinitialisé'), ('DECISION', 'Décision'), ('REGLEMENT', 'Règlement'), ('IMPORT', 'Import en masse'), ('CARTE', 'Carte éditée'), ('INTEGRITE', "Alerte d'intégrité"), ('ACCES_DPI', 'Accès dossier patient')], db_index=True, max_length=20),
        ),
    ]
