# Generated by Django 5.2.16 on 2026-07-14 17:52

import accounts.managers
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='nom')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('ASSURE', 'Assuré'), ('MEDECIN', 'Médecin'), ('PHARMACIEN', 'Pharmacien')], db_index=True, max_length=20, verbose_name='rôle')),
                ('is_staff', models.BooleanField(default=False, verbose_name='accès au back-office')),
                ('is_active', models.BooleanField(default=True, verbose_name='compte actif')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
