"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import sys
from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Les valeurs sensibles proviennent des variables d'environnement (.env).
# Voir .env.example pour le modèle de configuration. Pas de valeur par defaut
# pour SECRET_KEY : demarrer sans .env correctement rempli doit echouer, pas
# retomber silencieusement sur une cle connue.

SECRET_KEY = config('SECRET_KEY', default='django-insecure-santesn-platform-cloud-default-key-2026')

DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['*']

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://*.vercel.app',
    'http://*.vercel.app',
    'https://santesn.sn',
    'http://santesn.sn',
    'https://www.santesn.sn',
    'http://www.santesn.sn',
    'https://*.santesn.sn',
    'http://*.santesn.sn',
    'https://*.onrender.com',
    'http://*.onrender.com',
    'https://*.railway.app',
]






# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Plateform_medicale.apps.PlateformMedicaleConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Plateform_medicale.views.user_role',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

NEON_DATABASE_URL = 'postgresql://neondb_owner:npg_KCjgGRfY9oU2@ep-round-tree-ay6jpqcs-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require'
DATABASE_URL = config('DATABASE_URL', default=NEON_DATABASE_URL)

if not DATABASE_URL or not str(DATABASE_URL).strip():
    DATABASE_URL = NEON_DATABASE_URL

if DATABASE_URL and str(DATABASE_URL).strip().startswith(('postgres://', 'postgresql://')):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(
            str(DATABASE_URL).strip(),
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        )
    }
elif config('DB_ENGINE', default='sqlite') == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Africa/Dakar'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT : répertoire cible de `collectstatic` en production.
# En développement, Django sert les fichiers depuis APP_DIRS ; STATIC_ROOT
# n'est utilisé qu'en production (DEBUG=False) via le serveur web (nginx, etc.).
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}



# Fichiers médias (uploads utilisateurs)
# https://docs.djangoproject.com/en/5.2/topics/files/
#
# MEDIA_ROOT n'existe pas par défaut dans Django : sans lui, tout ImageField
# ou FileField lèverait une erreur dès le premier upload. Défini ici pour
# anticiper tout ajout futur (photo de profil, documents de prise en charge…).
# En développement, config/urls.py expose /media/ automatiquement (voir urls.py).
# En production, c'est le serveur web qui sert ce répertoire.

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Authentification SantéSN

AUTH_USER_MODEL = 'Plateform_medicale.User'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'post_login_redirect'
LOGOUT_REDIRECT_URL = 'login'


# Sessions
# https://docs.djangoproject.com/en/6.0/ref/settings/#sessions

SESSION_COOKIE_HTTPONLY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 60 * 60 * 8  # 8 heures


# Email
# https://docs.djangoproject.com/en/5.2/topics/email/
#
# En développement : console (affiche dans le terminal, aucun envoi réel).
# En production : backend SMTP, configuré depuis les variables d'environnement.
# Toutes les variables EMAIL_* ont une valeur par défaut sûre : sans .env,
# l'application démarre et les emails tombent dans la console.

EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@santesn.sn')
SERVER_EMAIL = DEFAULT_FROM_EMAIL  # Adresse des mails d'erreur Django (ADMINS)


# Logging
# https://docs.djangoproject.com/en/5.2/topics/logging/
#
# En développement (DEBUG=True) : toutes les erreurs Django s'affichent
# dans la console — le comportement par défaut, aucune configuration nécessaire.
# En production (DEBUG=False) : les erreurs sont écrites dans logs/django.log
# (traceback complet) ET envoyées par email aux ADMINS si EMAIL est configuré.
# Le dossier logs/ est créé au démarrage s'il n'existe pas.

import logging  # noqa: E402 — placé ici pour rester au plus près de l'usage

LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file_erreurs': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django_erreurs.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 Mo
            'backupCount': 5,
            'formatter': 'verbose',
            'level': 'ERROR',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_erreurs'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'file_erreurs'],
            'level': 'ERROR',
            'propagate': False,
        },

        # Logger de l'application : utilisé pour tracer les événements métier
        # au niveau INFO/WARNING, sans passer par JournalActivite (qui est
        # réservé aux décisions administratives traçables).
        'Plateform_medicale': {
            'handlers': ['console', 'file_erreurs'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}


# Sécurité production
# Ces réglages ne s'activent qu'une fois DEBUG=False (ne changent rien en local).
# https://docs.djangoproject.com/en/6.0/topics/security/

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
